### ISSUE TITLE
Add classes to `wt_()` returns

### ISSUE THREAD

**Issue by malcolmbarrett** [r-causal/propensity#3]
important weights class from tidymodels + a class to indicate the type of weight, e.g. `ato_weight`, which can help us indicate which sandwich estimator to fit

cc @simonpcouch because this idea came from your code. In other words, we can move the step of indicating this is a weight we can use in tidymodels to propensity

**Comment by simonpcouch** [comment]
Stoked to hear you're motivated to tighten that integration. :)

Wanted to note that our [current drafts](https://github.com/tidymodels/tune/pull/679) of machinery introducing support for propensity [take care of that conversion under the hood](https://github.com/tidymodels/workflows/blob/propensity-tune%23625/R/weight_propensity.R#L37-L39).

**Comment by malcolmbarrett** [comment]
Cool, I think that will work a bit better since the importance weights class object turned out to be difficult to work with in other ways we use them
